<?php declare(strict_types = 1);

namespace Netmosfera\PHPCSSAST\FastTokenizer;

class Data
{
    public const SPLIT = '/([\\x{5f}-\\x{5f}\\x{67}-\\x{7a}\\x{47}-\\x{5a}]+|[\\x{3a}-\\x{40}\\x{7b}-\\x{7e}\\x{5b}-\\x{5e}\\x{21}-\\x{2f}\\x{60}-\\x{60}]+|[\\x{61}-\\x{66}\\x{41}-\\x{46}]+|[\\x{20}-\\x{20}\\x{9}-\\x{a}\\x{c}-\\x{d}]+|[\\x{30}-\\x{39}]+|[\\x{b}-\\x{b}\\x{e}-\\x{1f}\\x{7f}-\\x{7f}\\x{1}-\\x{8}]+|[\\x{80}-\\x{10ffff}\\x{0}-\\x{0}]+)/usD';
    public const RECOGNIZE_GROUPS = array (
  'A' => 
  array (
    '_' => true,
    'g' => true,
    'h' => true,
    'i' => true,
    'j' => true,
    'k' => true,
    'l' => true,
    'm' => true,
    'n' => true,
    'o' => true,
    'p' => true,
    'q' => true,
    'r' => true,
    's' => true,
    't' => true,
    'u' => true,
    'v' => true,
    'w' => true,
    'x' => true,
    'y' => true,
    'z' => true,
    'G' => true,
    'H' => true,
    'I' => true,
    'J' => true,
    'K' => true,
    'L' => true,
    'M' => true,
    'N' => true,
    'O' => true,
    'P' => true,
    'Q' => true,
    'R' => true,
    'S' => true,
    'T' => true,
    'U' => true,
    'V' => true,
    'W' => true,
    'X' => true,
    'Y' => true,
    'Z' => true,
  ),
  'S' => 
  array (
    ':' => true,
    ';' => true,
    '<' => true,
    '=' => true,
    '>' => true,
    '?' => true,
    '@' => true,
    '{' => true,
    '|' => true,
    '}' => true,
    '~' => true,
    '[' => true,
    '\\' => true,
    ']' => true,
    '^' => true,
    '!' => true,
    '"' => true,
    '#' => true,
    '$' => true,
    '%' => true,
    '&' => true,
    '\'' => true,
    '(' => true,
    ')' => true,
    '*' => true,
    '+' => true,
    ',' => true,
    '-' => true,
    '.' => true,
    '/' => true,
    '`' => true,
  ),
  'H' => 
  array (
    'a' => true,
    'b' => true,
    'c' => true,
    'd' => true,
    'e' => true,
    'f' => true,
    'A' => true,
    'B' => true,
    'C' => true,
    'D' => true,
    'E' => true,
    'F' => true,
  ),
  'W' => 
  array (
    ' ' => true,
    '	' => true,
    '
' => true,
    '' => true,
    '' => true,
  ),
  'D' => 
  array (
    0 => true,
    1 => true,
    2 => true,
    3 => true,
    4 => true,
    5 => true,
    6 => true,
    7 => true,
    8 => true,
    9 => true,
  ),
  'I' => 
  array (
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
    '' => true,
  ),
);
    public const RECOGNIZE_NON_ASCII = '/^[\\x{80}-\\x{10ffff}\\x{0}-\\x{0}]/usD';
}
